### ISSUE TITLE
Module not found when Generate

### ISSUE THREAD

**Issue by GiantHoax** [magesuite/magepack#74]
When i run magepack generate I get the following error:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'puppeteer'

How can I fix this?

**Comment by kodakuten-ab** [comment]
Hi guys, we've the same issue here also. Using Ubuntu 18.04. But we've managed to make it work on another server using Ubuntu 20.04 so maybe something there causing this? Anyone got any clues?

**Comment by juhanihaapala** [comment]
`sudo npm install -g puppeteer`

Fixed this for me last time with ubuntu 20.04.
