### ISSUE TITLE
Fotorama JS issues on Product Pages

### ISSUE THREAD

**Issue by ryan-copeland** [magesuite/magepack#60]
With Magepack JS bundling enabled the media gallery on product pages does not work. I am getting the following JS error message in the console:

Uncaught TypeError: settings.$elementF.fotorama is not a function (gallery.js:297)
    at UiClass.initGallery (gallery.js:297)
    at UiClass.initialize (gallery.js:139)
    at UiClass.initialize (bundle-common.js:23120)
    at UiClass (bundle-common.js:39723)
    at bundle-common.js:27903
    at Object.execCb (487d101294ff3aac824d253a5735ab97.js:1650)
    at Module.check (487d101294ff3aac824d253a5735ab97.js:866)
    at Module.<anonymous> (487d101294ff3aac824d253a5735ab97.js:1113)
    at 487d101294ff3aac824d253a5735ab97.js:132
    at 487d101294ff3aac824d253a5735ab97.js:1156

Everything works fine when JS bundling is disabled. Has anyone else experienced the same issue?

**Comment by btekbtek** [comment]
I have same issue after update from Magento 2.3.4-p2 to 2.4.1.

When bundle disable everything is fine.

Same error like yours with 2 others:
Uncaught TypeError: imgLazy.lazyload is not a function

and

Uncaught TypeError: $(...).magicaccordion is not a function

**Comment by sreenathnr555** [comment]
Any update on this?

After enabling magepack JS bundling,media gallery in the product details page does not work. **Magento** version is 2.3.4.
The error shown in the console is 
```
uncaught TypeError: settings.$elementF.fotorama is not a function (gallery.js:297)
at UiClass.initGallery (bundle-product.js:15952)
at UiClass.initialize (bundle-product.js:15794)
at UiClass.initialize (bundle-common.js:23102)
at UiClass (bundle-common.js:44800)
at bundle-common.js:27885
at Object.execCb (487d101294ff3aac824d253a5735ab97.js:1650)
at Module.check (487d101294ff3aac824d253a5735ab97.js:866)
at Module.enable (487d101294ff3aac824d253a5735ab97.js:1143)
at Module.init (487d101294ff3aac824d253a5735ab97.js:774)
at 487d101294ff3aac824d253a5735ab97.js:1416
```

**Comment by sunilit42** [comment]
Hello,

Any solution for that?

**Comment by nabeelfocus** [comment]
Hi,

Any solution for that?
